### ISSUE TITLE
Error LNK2019 when building

### ISSUE THREAD

**Issue by lazachemou** [gnebehay/OpenTLD#56]
Hello,
I am using Windows 7 64bits, Visual Studio 2013 and OpenCV 2411.
I think I linked everything to link in the properties of both projects main and opentld. When I build separately the main project first, there is no error, just somes warnings and main.lib is created. But when I try to build opentld or all the projects, I have 11 errors:

"error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl libconfig::Setting::operator int(void)const " (__imp_??BSetting@libconfig@@QEBAHXZ) referenced in function "public: int __cdecl tld::Config::init(int,char * *)" (?init@Config@tld@@QEAAHHPEAPEAD@Z)	C:\Users\marie.burckbuchler\Documents\GitHub "
in file: main.lib(Config.obj) in the project opentld

all the errors are similar to each other.

And there are a lot of Warnings: 134, mostly:
"warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)"
in file libconfig.hpp	on different lines in the project main

Could someone give me a clue on what could be the problem?
Thank you!

**Comment by lazachemou** [comment]
I don't know what was the error exacty, but I re-downloaded the code and I re-parametered the links and so on and now it works.
